name: talent_showcase_app
description: "A flutter project where users showcase talents, interact via
  posts/comments, and manage profiles."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.6
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  formz: ^0.8.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  socket_io_client: ^3.1.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins_Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins_Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins_SemiBold.ttf
          weight: 600
